DOMAIN = "hayward_aquaconnect"
DEFAULT_NAME = "Hayward AquaConnect"
DEFAULT_SCAN_INTERVAL = 5
DEFAULT_COMMAND_TIMEOUT = 10
DEFAULT_COMMAND_RETRIES = 1
DEFAULT_BUTTON_DELAY = 0.75

CONF_COMMAND_TIMEOUT = "command_timeout"
CONF_COMMAND_RETRIES = "command_retries"
CONF_BUTTON_DELAY = "button_delay"
CONF_SLOT_OVERRIDES = "slot_overrides"

MANUFACTURER = "Hayward"
MODEL = "AQ-CO-HOMENET / AquaConnect"
